# -*- coding: utf-8 -*-
"""Image Recogniton (KNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us5lROJ6wzL7rQGmJ47uoxSecnfNHL3N
"""

from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()
X, y = mnist["data"], mnist["target"]
X.shape
y.shape

X.head()

y.head()

import numpy as np
import matplotlib.pyplot as plt

examp = X.iloc[2]
examp

examp_image = np.reshape(np.ravel(examp), (28, 28))

plt.imshow(examp_image, cmap='binary')
plt.axis("off")
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

y_test

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
y_pred

accuracy = accuracy_score(y_test, y_pred)
accuracy

examp2 = X_test.iloc[100]
examp2

examp2_image = np.reshape(np.ravel(examp2), (28, 28))

plt.imshow(examp2_image, cmap='binary')
plt.axis("off")
plt.show()

y_pred[100]